# Generated by Django 4.2.4 on 2023-09-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_contactinfo_personalinfo_rename_curso_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
