# Generated by Django 4.2.4 on 2023-09-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_personalinfo_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Curso',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
