# Generated by Django 4.2.5 on 2023-09-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_perfil_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=24, unique=True, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=50)),
                ('cuerpo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
